### ISSUE TITLE
Mapa mental Web 3.0

### ISSUE THREAD

**Issue by uzias10** [SistemasTecTlaxiaco/mapa-mental-web-3-uzias10#1]
[Tecnologia 3.0.pdf](https://github.com/SistemasTecTlaxiaco/mapa-mental-web-3-uzias10/files/8373746/Tecnologia.3.0.pdf)

**Comment by Abraham890** [comment]
Calificación:  20 puntos

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
